import type { Metadata } from "next";
import "./globals.css";
import { Gaegu } from 'next/font/google';
import Navbar from "@/components/navbar";

const gaegu = Gaegu({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: "Home | Anon Leta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`mx-auto ${gaegu.className} ${gaegu.className} antialiased bg-stone-100 text-stone-900 text-xl bg-dot max-w-[2000px]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
